// ============================================================
// Country name (RU / EN) → ISO 3166-1 alpha-3 mapping.
// Used to plot AppMetrica `regionCountry` results (which arrive
// as Russian or English country names) on the world map.
// world-atlas TopoJSON keys countries by ISO 3166-1 numeric id,
// but exposes ISO_A3 as a property of each feature.
// ============================================================

const COUNTRY_NAME_TO_ISO3: Record<string, string> = {
  // CIS / Central Asia
  Россия: "RUS",
  Russia: "RUS",
  Узбекистан: "UZB",
  Uzbekistan: "UZB",
  Казахстан: "KAZ",
  Kazakhstan: "KAZ",
  Кыргызстан: "KGZ",
  Киргизия: "KGZ",
  Kyrgyzstan: "KGZ",
  Таджикистан: "TJK",
  Tajikistan: "TJK",
  Туркменистан: "TKM",
  Turkmenistan: "TKM",
  Беларусь: "BLR",
  Белоруссия: "BLR",
  Belarus: "BLR",
  Украина: "UKR",
  Ukraine: "UKR",
  Молдова: "MDA",
  Молдавия: "MDA",
  Moldova: "MDA",
  Грузия: "GEO",
  Georgia: "GEO",
  Армения: "ARM",
  Armenia: "ARM",
  Азербайджан: "AZE",
  Azerbaijan: "AZE",
  // Europe
  Германия: "DEU",
  Germany: "DEU",
  Великобритания: "GBR",
  "United Kingdom": "GBR",
  UK: "GBR",
  Франция: "FRA",
  France: "FRA",
  Италия: "ITA",
  Italy: "ITA",
  Испания: "ESP",
  Spain: "ESP",
  Польша: "POL",
  Poland: "POL",
  Нидерланды: "NLD",
  Netherlands: "NLD",
  Бельгия: "BEL",
  Belgium: "BEL",
  Швеция: "SWE",
  Sweden: "SWE",
  Норвегия: "NOR",
  Norway: "NOR",
  Финляндия: "FIN",
  Finland: "FIN",
  Дания: "DNK",
  Denmark: "DNK",
  Швейцария: "CHE",
  Switzerland: "CHE",
  Австрия: "AUT",
  Austria: "AUT",
  Чехия: "CZE",
  Czechia: "CZE",
  "Czech Republic": "CZE",
  Словакия: "SVK",
  Slovakia: "SVK",
  Венгрия: "HUN",
  Hungary: "HUN",
  Румыния: "ROU",
  Romania: "ROU",
  Болгария: "BGR",
  Bulgaria: "BGR",
  Греция: "GRC",
  Greece: "GRC",
  Португалия: "PRT",
  Portugal: "PRT",
  Ирландия: "IRL",
  Ireland: "IRL",
  Литва: "LTU",
  Lithuania: "LTU",
  Латвия: "LVA",
  Latvia: "LVA",
  Эстония: "EST",
  Estonia: "EST",
  Сербия: "SRB",
  Serbia: "SRB",
  Хорватия: "HRV",
  Croatia: "HRV",
  Турция: "TUR",
  Turkey: "TUR",
  Türkiye: "TUR",
  // Asia
  Китай: "CHN",
  China: "CHN",
  Япония: "JPN",
  Japan: "JPN",
  "Южная Корея": "KOR",
  "Republic of Korea": "KOR",
  "South Korea": "KOR",
  Индия: "IND",
  India: "IND",
  Пакистан: "PAK",
  Pakistan: "PAK",
  Иран: "IRN",
  Iran: "IRN",
  Ирак: "IRQ",
  Iraq: "IRQ",
  "Саудовская Аравия": "SAU",
  "Saudi Arabia": "SAU",
  ОАЭ: "ARE",
  "United Arab Emirates": "ARE",
  Израиль: "ISR",
  Israel: "ISR",
  Афганистан: "AFG",
  Afghanistan: "AFG",
  Вьетнам: "VNM",
  Vietnam: "VNM",
  Таиланд: "THA",
  Thailand: "THA",
  Малайзия: "MYS",
  Malaysia: "MYS",
  Индонезия: "IDN",
  Indonesia: "IDN",
  Сингапур: "SGP",
  Singapore: "SGP",
  Филиппины: "PHL",
  Philippines: "PHL",
  // Americas
  США: "USA",
  "United States": "USA",
  USA: "USA",
  Канада: "CAN",
  Canada: "CAN",
  Мексика: "MEX",
  Mexico: "MEX",
  Бразилия: "BRA",
  Brazil: "BRA",
  Аргентина: "ARG",
  Argentina: "ARG",
  Чили: "CHL",
  Chile: "CHL",
  Колумбия: "COL",
  Colombia: "COL",
  // Africa
  Египет: "EGY",
  Egypt: "EGY",
  ЮАР: "ZAF",
  "South Africa": "ZAF",
  Нигерия: "NGA",
  Nigeria: "NGA",
  Марокко: "MAR",
  Morocco: "MAR",
  // Oceania
  Австралия: "AUS",
  Australia: "AUS",
  "Новая Зеландия": "NZL",
  "New Zealand": "NZL",
};

export const countryNameToIso3 = (name: string | null | undefined): string | null => {
  if (!name) return null;
  const trimmed = String(name).trim();
  if (!trimmed) return null;
  // Direct match
  if (COUNTRY_NAME_TO_ISO3[trimmed]) return COUNTRY_NAME_TO_ISO3[trimmed];
  // Case-insensitive fallback
  const lower = trimmed.toLowerCase();
  for (const [k, v] of Object.entries(COUNTRY_NAME_TO_ISO3)) {
    if (k.toLowerCase() === lower) return v;
  }
  return null;
};
